export enum GameModule {
    Override = 'invalid',
    Base = 'Base',
    CorpEra = 'Corp Era',
    Promo = 'Promo',
    Venus = 'Venus',
    Colonies = 'Colonies',
    Prelude = 'Prelude',
    Turmoil = 'Turmoil',
    Community = 'Community',
    Ares = 'Ares',
    Moon = 'Moon',
    Leader = 'Leader',
    Automa = 'Automa',
}
